### ISSUE TITLE
No Content for Latest APIs for public resources 

### ISSUE THREAD

**Issue by m-arun** [datakaveri/iudx-resource-server#172]
Response is 204 for Latest queries on any public resources on the catalogue.
Below is a cURL for example:
curl --location --request GET 'https://rs.iudx.org.in/ngsi-ld/v1/entities/suratmunicipal.org/6db486cb4f720e8585ba1f45a931c63c25dbbbda/rs.iudx.org.in/surat-itms-additional-info/surat-itms-depot-info' \
--header 'token: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJzdWIiOiI0NGI2MGVmNC1hMjZmLTRlOTctOWEzOS05OGIyNzg0M2EyMmIiLCJpc3MiOiJhdXRob3JpemF0aW9uLml1ZHgub3JnLmluIiwiYXVkIjoicnMuaXVkeC5vcmcuaW4iLCJleHAiOjE2Mzg5MTI4NDEsImlhdCI6MTYzODg2OTY0MSwiaWlkIjoicnM6cnMuaXVkeC5vcmcuaW4iLCJyb2xlIjoiY29uc3VtZXIiLCJjb25zIjp7fX0.EyWw14TkO_0bhJfYZmdZ8Nbz_OJPb93ty37SW3TJ3f_y10nZUuuFWtIv-jz5ZdpQVduO0Gd-riWQtJHUjhsvxQ'

**Comment by abhi4578** [comment]
- This is mostly applicable to only, some static resources,  like one above. This may be because it has not published lately, i.e . not after IUDX 3.0 release (Oct 27).  In IUDX 3.0 release, latest data store was changed from elasticsearch to redis ( the latest data was not migrated).
-  The dynamic data/ anything that has publish  like air quality data for pune, available https://catalogue.iudx.org.in/dataset/datakaveri.org-04a15c9960ffda227e9546f3f46e629e1fe4132b-rs.iudx.org.in-pune-env-aqm 
- The solution would be to re-run the adapters of static/static like ( i.e not published from Oct 27, eg: places of interest, above item ) resources, so that the data will be available through latest api.

**Comment by abhi4578** [comment]
>     * The solution would be to re-run the adapters of static/static like ( i.e not published from Oct 27, eg: places of interest, above item ) resources, so that the data will be available through latest api.

But the problem would be this would create duplicated data in Elasticsearch @swaminathanvasanth . Unless we bound these adapter to only redis-latest queue

**Comment by abhi4578** [comment]
for static data, if you publishes again , won't their be duplication of data in elasticsearch as it already has it. Need to think over

**Comment by abhi4578** [comment]
This done. and static data  is now available through latest api . closing the issue
